name: tejwal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.19.6
  google_sign_in: ^5.4.4
  google_maps_flutter: ^2.1.1
  location: ^6.0.2
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.7
  crypto: ^3.0.1
  http: ^1.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  provider: ^6.0.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  dropdown_search: ^5.0.6
  cached_network_image: ^3.3.1
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/shaders/ink_sparkle.frag
